address: bar.com:2002
discovery: dambli
concurrency: 1
deployDataDir: .bw
deployTimeout: 1h0m0s
deployPrompt: are you sure you want to deploy? (remove this field to disable the prompt)
credentialsSource: ""
credentialsDir: /shared/jatone/.config/bearded-wookie/foo
ca: /shared/jatone/.config/bearded-wookie/foo/tlsca.cert
servername: bar.com
environment: |
  FOO=BAR
